# Generated by Django 2.1.7 on 2021-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='ItemStatus',
            field=models.CharField(choices=[(0, 'PENDING'), (1, 'BOUGHT'), (0, 'NOT AVAILABLE')], max_length=50),
        ),
    ]
