# Generated by Django 2.1.7 on 2021-03-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210303_0057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocerylist',
            table=None,
        ),
    ]
