# Generated by Django 2.1.7 on 2021-03-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210303_0134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocerylist',
            table='Grocery_list',
        ),
    ]
