# Generated by Django 2.1.7 on 2021-03-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210303_0139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocerylist',
            table='list_of_grocery',
        ),
    ]
